### ISSUE TITLE
Safari z-index issues

### ISSUE THREAD

**Issue by floogulinc** [UMM-CSci-3601-F17/iteration-2-cheezit#128]
In the play component and join game component the first toolbar appears over the second and not as one single toolbar. Also the invite to game button is missing.

Putting this in styles.scss fixes the double toolbar part:
```css
td-layout-nav .mat-toolbar { 
    position: relative; 
    z-index: 0; 
} 
```
But I'm having trouble with the invite to game button.
